bot:
      token: ${BOT_TOKEN}

spring:
      datasource:
            url: ${SPRING_DATASOURCE_URL}
            username: ${SPRING_DATASOURCE_USERNAME}
            password: ${SPRING_DATASOURCE_PASSWORD}

      jpa:
            hibernate:
                  ddl-auto: update
            show-sql: false

logging:
      level:
            org.hibernate.SQL: warn
            org.hibernate.type.descriptor.sql: warn

app:
      admins:
            - 459307336
            - 1632772141

      superAdmins:
            - 459307336

      info:
            url: https://masters-league.com/tours/



      masters-api:
            url: https://masters-league.com/wp-admin/admin-ajax.php
            method: POST
            user-agent: Mozilla/5.0
            action: tourslist
            country: RUS
            timeout: 10000



