bot:
      token: ${BOT_TOKEN}

spring:
      datasource:
            url: jdbc:postgresql://localhost:5432/botdb
            username: botuser
            password: 1234

      jpa:
            hibernate:
                  ddl-auto: update
            show-sql: false

logging:
      level:
            org.telegram.telegrambots: WARN   # 👈 ВОТ ЭТО ДОБАВИЛИ
            org.hibernate.SQL: warn
            org.hibernate.type.descriptor.sql: warn

app:
      admins:
            - 459307336
            - 1632772141
            - 1332165567

      superAdmins:
            - 459307336

      info:
            url: https://masters-league.com/



      masters-api:
            url: https://masters-league.com/wp-admin/admin-ajax.php
            method: POST
            user-agent: Mozilla/5.0
            action: tourslist
            country: RUS
            timeout: 20000





