spring:
      datasource:
            url: jdbc:postgresql://db:5432/botdb
            username: botuser
            password: 1234
      jpa:
            hibernate:
                  ddl-auto: none
            show-sql: false
      flyway:
            enabled: true
            locations: classpath:db/migration
            baseline-on-migrate: true
            baseline-version: 0
      mail:
            host: sm17.hosting.reg.ru
            port: 465
            username: noreply@pulsecore-app.ru
            password: FJ3-wT5-7ye-Rfm
            protocol: smtps
            properties:
                  mail:
                        smtp:
                              auth: true
                              starttls:
                                    enable: true

logging:
      level:
            org.hibernate.SQL: warn
            org.flywaydb: debug

app:
      masters-api:
            url: https://masters-league.com/wp-admin/admin-ajax.php
            method: POST
            user-agent: Mozilla/5.0
            action: tourslist
            country: RUS
            timeout: 20000
      mail:
            from: PulseCore <noreply@pulsecore-app.ru>
            verification:
                  subject: PulseCore — Код подтверждения
                  text: "Ваш код подтверждения: %s\n\nВведите его в приложении."