-- baseline (не будет выполняться)

-- players
CREATE TABLE players (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         telegram_id BIGINT NOT NULL UNIQUE,
                         name VARCHAR(255) NOT NULL UNIQUE,
                         created_at TIMESTAMP,
                         is_blocked BOOLEAN
);

-- tournament
CREATE TABLE tournament (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            external_id BIGINT NOT NULL UNIQUE,
                            link VARCHAR(255),
                            date DATE,
                            time VARCHAR(255),
                            started BOOLEAN NOT NULL,
                            finished BOOLEAN NOT NULL,
                            cancelled BOOLEAN DEFAULT FALSE,
                            processed BOOLEAN DEFAULT FALSE
);

-- tournament_results
CREATE TABLE tournament_results (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    player_id BIGINT NOT NULL,
                                    tournament_id BIGINT NOT NULL,
                                    player_name VARCHAR(255) NOT NULL,
                                    amount DOUBLE PRECISION NOT NULL,
                                    date DATE NOT NULL,
                                    is_night BOOLEAN NOT NULL,
                                    bonus DOUBLE PRECISION,
                                    CONSTRAINT uq_tr UNIQUE (player_id, tournament_id),
                                    CONSTRAINT fk_tr_player FOREIGN KEY (player_id) REFERENCES players(id),
                                    CONSTRAINT fk_tr_tournament FOREIGN KEY (tournament_id) REFERENCES tournament(id)
);

-- player_notification
CREATE TABLE player_notification (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     player_id BIGINT NOT NULL,
                                     tournament_id BIGINT NOT NULL,
                                     reminder_sent BOOLEAN NOT NULL,
                                     evening_sent BOOLEAN NOT NULL,
                                     hall INTEGER,
                                     CONSTRAINT uq_pn UNIQUE (player_id, tournament_id),
                                     CONSTRAINT fk_pn_player FOREIGN KEY (player_id) REFERENCES players(id),
                                     CONSTRAINT fk_pn_tournament FOREIGN KEY (tournament_id) REFERENCES tournament(id)
);