CREATE TABLE IF NOT EXISTS lineup (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      league VARCHAR(50) NOT NULL,
    time VARCHAR(10) NOT NULL,
    players TEXT NOT NULL,
    date DATE NOT NULL,
    city VARCHAR(100) NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_lineup_date_city
    ON lineup (date, city);